version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server-node

  server-node:
    build: ./server-node
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - server-python

  server-python:
    build: ./server-python
    ports:
      - "5000:5000"
